// Optional imperative WebMCP surface; ordinary browsers need no polyfill.
export function registerAgentTools(app){
  const context=document.modelContext;if(!context?.registerTool)return;
  const lifecycle=new AbortController();window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
  const add=tool=>{try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(e=>console.warn('Optional agent tool unavailable',e));}catch(e){console.warn('Optional agent tool unavailable',e);}};
  add({name:'read_atlas_state',description:'Read the current atlas page, chapter, playback and visible layer IDs.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>({page:app.page,chapterId:app.playback.chapter.id,progress:app.playback.progress,playing:app.playback.playing,visibleLayers:app.visibleLayers().filter(l=>app.visibility()(l)).map(l=>l.id)})});
  add({name:'navigate_atlas_chapter',description:'Open Home and select a chapter, without changing the map camera or saved content.',inputSchema:{type:'object',properties:{chapterId:{type:'string'}},required:['chapterId'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:input=>{const i=app.doc.chapters.findIndex(c=>c.id===input?.chapterId);if(i<0)throw Error('Unknown chapter');app.setPage('home');app.playback.seek(i);return {chapterId:app.playback.chapter.id};}});
  add({name:'set_visible_atlas_layers',description:'Set the visible layers on the current page. This pins manual visibility until page defaults are restored.',inputSchema:{type:'object',properties:{layerIds:{type:'array',items:{type:'string'}}},required:['layerIds'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:input=>{const layers=app.visibleLayers();if(!Array.isArray(input?.layerIds)||input.layerIds.some(id=>!layers.some(l=>l.id===id)))throw Error('Unknown layer on this page');app.overrides[app.page]=Object.fromEntries(layers.map(l=>[l.id,input.layerIds.includes(l.id)]));app.render();return {visibleLayers:input.layerIds};}});
}
